# -*- coding: utf-8 -*-
"""Conway

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r0A9Gr_Dl8owUktTXRc2OVoI9-tlWcQE
"""

import numpy as np
import matplotlib.pyplot as plt
sz=100
world=[[0 for i in range(sz)] for j in range(sz)]

neighbors =[[0 for i in range(sz)] for j in range(sz)]

for i in range(1, sz-1):
  for j in range(1,sz-1):
    if(np.random.randint(2)>=1):
      world[i][j]=1

while(True):
  for row in range(1, len(world)-1):
    for cell in range(1,len(world[row])-1):
      if(world[row][cell]==1):
        for i in range(row-1,row+2):
          for j in range(cell-1,cell+2):
              neighbors[i][j]+=1
        neighbors[row][cell]-=1

  for i in range(1, sz-1):
    for j in range(1,sz-1):
      if(world[i][j]==1 and (neighbors[i][j]!=2 and neighbors[i][j]!=3)):
        world[i][j]=0
      elif(neighbors[i][j]==3):
        world[i][j]=1
      neighbors[i][j]=0

 
  plt.imshow(world)
  plt.show()